name: 'CI'

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.show }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - show: 'Ubuntu x64 Debug'
            os: ubuntu-latest
            proc: x64
            type: Debug
            coverage: false
          - show: 'Windows x64 Debug'
            os: windows-latest
            proc: x64
            type: Debug
            coverage: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      run: cmake -S . -B ${{ matrix.proc }}/${{ matrix.type }} -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/${{ matrix.proc }}/${{ matrix.type }}

    - name: Build
      run: cmake --build ${{ matrix.proc }}/${{ matrix.type }}

    - name: Install
      run: cmake --build ${{ matrix.proc }}/${{ matrix.type }} --target install