name: 'CI'

on:
  workflow_dispatch:

jobs:
  my_cmake_job:
    runs-on: ${{ matrix.os }}
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        proc: [x86, x64]
        type: [Debug, RelWithDebInfo]
        coverage: [false]
        include:
          - os: ubuntu-latest
            proc: x64
            type: Debug
            coverage: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      run: cmake -S . -B ${{ matrix.proc }}/${{ matrix.type }} -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/${{ matrix.proc }}/${{ matrix.type }}

    - name: Build
      run: cmake --build ${{ matrix.proc }}/${{ matrix.type }}

    - name: Install
      run: cmake --build ${{ matrix.proc }}/${{ matrix.type }} --target install