name: 'CI'

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.show }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - show: 'Ubuntu x64 Debug'
            os: ubuntu-latest
            arch: x64
            type: Debug
            preset: 'X64D'
            coverage: false
          - show: 'Windows x64 Debug'
            os: windows-latest
            arch: x64
            type: Debug
            msvc: true
            ilammy: x64
            preset: 'W64D'
            coverage: false
          - show: 'Windows x86 Debug'
            os: windows-latest
            arch: x86
            type: Debug
            msvc: true
            ilammy: x86_amd64
            preset: 'W32D'
            coverage: false

    steps:
    - name: MSVC variables
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.msvc }}
      with:
        arch: ${{ matrix.ilammy }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      run: cmake -S . -B ${{ matrix.arch }}/${{ matrix.type }} --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build ${{ matrix.arch }}/${{ matrix.type }}

    - name: Install
      run: cmake --build ${{ matrix.arch }}/${{ matrix.type }} --target install