name: 'CI'

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.show }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - show: 'Ubuntu x64 Debug'
            os: ubuntu-latest
            proc: x64
            type: Debug
            preset: 'X64D'
            coverage: false
          - show: 'Ubuntu x86 Debug'
            os: ubuntu-latest
            proc: x86
            type: Debug
            preset: 'X32D'
            coverage: false
          - show: 'Windows x64 Debug'
            os: windows-latest
            proc: x64
            type: Debug
            preset: 'W64D'
            coverage: false
          - show: 'Windows x86 Debug'
            os: windows-latest
            proc: x86
            type: Debug
            preset: 'W32D'
            coverage: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      run: cmake -S . -B ${{ matrix.proc }}/${{ matrix.type }} --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build ${{ matrix.proc }}/${{ matrix.type }}

    - name: Install
      run: cmake --build ${{ matrix.proc }}/${{ matrix.type }} --target install